# Generated by Django 4.1.7 on 2023-09-25 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.TextField(db_column="rooms_name", max_length=20, null=True),
                ),
                ("price", models.IntegerField(db_column="_price")),
                ("star", models.IntegerField(db_column="_star")),
                ("rooms", models.TextField(db_column="rooms_available", null=True)),
                ("features", models.TextField(db_column="_features", max_length=50)),
                (
                    "hotel_image",
                    models.ImageField(db_column="_hotelimage", upload_to="images/"),
                ),
            ],
            options={
                "db_table": "add_hotel",
            },
        ),
        migrations.CreateModel(
            name="Guides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                ("first_name", models.TextField(db_column="f_name", max_length=30)),
                ("last_name", models.TextField(db_column="l_name", max_length=30)),
                ("gender", models.CharField(db_column="gender", max_length=6)),
                ("dateofbirth", models.DateField(db_column="date_of_birth")),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                (
                    "address",
                    models.TextField(db_column="company_address", max_length=50),
                ),
                (
                    "country",
                    models.TextField(db_column="company_country", max_length=50),
                ),
                ("mobile", models.TextField(db_column="mobile_number", max_length=50)),
                ("email", models.TextField(db_column="company_email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "guides",
            },
        ),
        migrations.CreateModel(
            name="Hotels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                (
                    "companyname",
                    models.TextField(db_column="company_name", max_length=50),
                ),
                ("reg_id", models.TextField(db_column="company_reg_id", max_length=50)),
                ("reg_year", models.DateField(db_column="company_reg_year")),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                ("address", models.TextField(db_column="address", max_length=50)),
                ("country", models.TextField(db_column="country", max_length=50)),
                ("mobile", models.TextField(db_column="mobile", max_length=50)),
                ("email", models.TextField(db_column="email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "hotels",
            },
        ),
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                (
                    "companyname",
                    models.TextField(db_column="company_name", max_length=50),
                ),
                ("reg_id", models.TextField(db_column="company_reg_id", max_length=50)),
                ("reg_year", models.DateField(db_column="company_reg_year")),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                ("address", models.TextField(db_column="address", max_length=50)),
                ("country", models.TextField(db_column="country", max_length=50)),
                ("mobile", models.TextField(db_column="mobile", max_length=50)),
                ("email", models.TextField(db_column="email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
            },
        ),
        migrations.CreateModel(
            name="vehicle_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(db_column="start_date")),
                ("end_date", models.DateField(db_column="end_date")),
                ("total_vehicles", models.IntegerField(db_column="total_vehicles")),
                ("total_days", models.IntegerField(db_column="total_days")),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.users",
                    ),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        db_column="hotel_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hgv.vehicles",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_bookings",
            },
        ),
        migrations.CreateModel(
            name="Hotel_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateField(db_column="check_in_date")),
                ("check_out", models.DateField(db_column="check_out_date")),
                ("members", models.TextField(db_column="members_list")),
                ("total_rooms", models.IntegerField(db_column="total_rooms")),
                ("total_days", models.IntegerField(db_column="total_days")),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
                (
                    "hotel_id",
                    models.ForeignKey(
                        db_column="hotel_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hgv.add_hotel",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.users",
                    ),
                ),
            ],
            options={
                "db_table": "hotelbookings",
            },
        ),
        migrations.CreateModel(
            name="Guide_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(db_column="start_date")),
                ("end_date", models.DateField(db_column="end_date")),
                ("total_days", models.IntegerField(db_column="total_days")),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
                (
                    "guide_id",
                    models.ForeignKey(
                        db_column="guide_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hgv.guides",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.users",
                    ),
                ),
            ],
            options={
                "db_table": "guide_bookings",
            },
        ),
        migrations.CreateModel(
            name="Add_vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.TextField(db_column="_model")),
                ("price", models.IntegerField(db_column="_price")),
                ("features", models.TextField(db_column="_features", max_length=50)),
                (
                    "vehicle_image",
                    models.ImageField(db_column="_vehicleimage", upload_to="images/"),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        db_column="vehicles_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hgv.vehicles",
                    ),
                ),
            ],
            options={
                "db_table": "add_vehicle",
            },
        ),
        migrations.AddField(
            model_name="add_hotel",
            name="hotel_id",
            field=models.ForeignKey(
                db_column="hotel_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hgv.hotels",
            ),
        ),
    ]
