# Generated by Django 4.1.7 on 2023-08-30 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Add_guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(db_column="first_name", max_length=50)),
                (
                    "second_name",
                    models.TextField(db_column="second_name", max_length=50),
                ),
                ("Address", models.TextField(db_column="address", max_length=100)),
                ("country", models.TextField(db_column="country")),
                ("price", models.IntegerField(db_column="price")),
                ("contact", models.TextField(db_column="contact")),
                ("email", models.TextField(db_column="email", max_length=50)),
                (
                    "account_no",
                    models.TextField(db_column="account no", max_length=50, null=True),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="ifsc code", max_length=50, null=True),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank name", max_length=50, null=True),
                ),
                (
                    "gui_image",
                    models.ImageField(db_column="guide_image", upload_to="images/"),
                ),
            ],
            options={
                "db_table": "add_guide",
            },
        ),
        migrations.CreateModel(
            name="Add_hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.TextField(db_column="_hotelname", max_length=50)),
                ("place", models.TextField(db_column="_place", max_length=50)),
                ("price", models.IntegerField(db_column="_price")),
                ("star", models.IntegerField(db_column="_star")),
                ("Address", models.TextField(db_column="_address", max_length=100)),
                ("contact", models.TextField(db_column="_contact")),
                ("rooms", models.TextField(db_column="rooms_available", null=True)),
                ("email", models.TextField(db_column="_email", max_length=50)),
                ("features", models.TextField(db_column="_features", max_length=50)),
                (
                    "account_no",
                    models.TextField(db_column="_account no", max_length=50, null=True),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="_ifsc code", max_length=50, null=True),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="_bank name", max_length=50, null=True),
                ),
                (
                    "hotel_image",
                    models.ImageField(db_column="_hotelimage", upload_to="images/"),
                ),
            ],
            options={
                "db_table": "add_hotel",
            },
        ),
        migrations.CreateModel(
            name="Add_vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_name",
                    models.TextField(db_column="_vehiclename", max_length=50),
                ),
                ("vehicle_id", models.IntegerField(db_column="_vehicleid")),
                ("model", models.TextField(db_column="_model")),
                ("price", models.IntegerField(db_column="_price")),
                ("address", models.TextField(db_column="_address", max_length=50)),
                ("contact", models.TextField(db_column="_contact")),
                ("email", models.TextField(db_column="_email", max_length=50)),
                ("features", models.TextField(db_column="_features", max_length=50)),
                (
                    "account_no",
                    models.TextField(db_column="_account no", max_length=50, null=True),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="_ifsc code", max_length=50, null=True),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="_bank name", max_length=50, null=True),
                ),
                (
                    "vehicle_image",
                    models.ImageField(db_column="_vehicleimage", upload_to="images/"),
                ),
            ],
            options={
                "db_table": "add_vehicle",
            },
        ),
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                (
                    "companyname",
                    models.TextField(db_column="company_name", max_length=50),
                ),
                ("regid", models.TextField(db_column="company_reg_id", max_length=50)),
                ("regyear", models.DateField(db_column="company_reg_year")),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                (
                    "address",
                    models.TextField(db_column="company_address", max_length=50),
                ),
                (
                    "country",
                    models.TextField(db_column="company_country", max_length=50),
                ),
                ("mobile", models.TextField(db_column="mobile_number", max_length=50)),
                ("email", models.TextField(db_column="company_email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "service",
            },
        ),
        migrations.CreateModel(
            name="Guides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                ("first_name", models.TextField(db_column="f_name", max_length=30)),
                ("last_name", models.TextField(db_column="l_name", max_length=30)),
                ("gender", models.CharField(db_column="gender", max_length=6)),
                ("dateofbirth", models.DateField(db_column="date_of_birth")),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                (
                    "address",
                    models.TextField(db_column="company_address", max_length=50),
                ),
                (
                    "country",
                    models.TextField(db_column="company_country", max_length=50),
                ),
                ("mobile", models.TextField(db_column="mobile_number", max_length=50)),
                ("email", models.TextField(db_column="company_email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "guides",
            },
        ),
        migrations.CreateModel(
            name="Hotels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                (
                    "companyname",
                    models.TextField(db_column="company_name", max_length=50),
                ),
                ("reg_id", models.TextField(db_column="company_reg_id", max_length=50)),
                ("reg_year", models.DateField(db_column="company_reg_year")),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                ("address", models.TextField(db_column="address", max_length=50)),
                ("country", models.TextField(db_column="country", max_length=50)),
                ("mobile", models.TextField(db_column="mobile", max_length=50)),
                ("email", models.TextField(db_column="email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "hotels",
            },
        ),
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                (
                    "companyname",
                    models.TextField(db_column="company_name", max_length=50),
                ),
                ("reg_id", models.TextField(db_column="company_reg_id", max_length=50)),
                ("reg_year", models.DateField(db_column="company_reg_year")),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                ("address", models.TextField(db_column="address", max_length=50)),
                ("country", models.TextField(db_column="country", max_length=50)),
                ("mobile", models.TextField(db_column="mobile", max_length=50)),
                ("email", models.TextField(db_column="email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
            },
        ),
    ]
