# Generated by Django 4.1.7 on 2023-09-25 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle_book",
            name="total_vehicles",
        ),
    ]
