# Generated by Django 4.1.7 on 2023-06-04 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catagory",
            old_name="company_name",
            new_name="companyname",
        ),
        migrations.RenameField(
            model_name="catagory",
            old_name="reg_id",
            new_name="regid",
        ),
        migrations.RenameField(
            model_name="catagory",
            old_name="reg_year",
            new_name="regyear",
        ),
        migrations.RenameField(
            model_name="catagory",
            old_name="user_catagory",
            new_name="usercatagory",
        ),
    ]
