# Generated by Django 4.1.7 on 2023-09-04 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_hotel",
            name="Address",
        ),
        migrations.RemoveField(
            model_name="add_hotel",
            name="account_no",
        ),
        migrations.RemoveField(
            model_name="add_hotel",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="add_hotel",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="add_hotel",
            name="email",
        ),
        migrations.RemoveField(
            model_name="add_hotel",
            name="hotel_name",
        ),
        migrations.RemoveField(
            model_name="add_hotel",
            name="ifsc_code",
        ),
        migrations.RemoveField(
            model_name="add_hotel",
            name="place",
        ),
    ]
