# Generated by Django 4.1.7 on 2023-09-04 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0002_remove_add_hotel_address_remove_add_hotel_account_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_vehicle",
            name="account_no",
        ),
        migrations.RemoveField(
            model_name="add_vehicle",
            name="address",
        ),
        migrations.RemoveField(
            model_name="add_vehicle",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="add_vehicle",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="add_vehicle",
            name="email",
        ),
        migrations.RemoveField(
            model_name="add_vehicle",
            name="ifsc_code",
        ),
    ]
