# Generated by Django 4.1.7 on 2023-09-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0002_remove_vehicle_book_total_vehicles"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide_book",
            name="status",
            field=models.TextField(db_column="status", default="", max_length=20),
        ),
    ]
