# Generated by Django 4.1.7 on 2023-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0002_rename_company_name_catagory_companyname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(db_column="first_name", max_length=50)),
                (
                    "second_name",
                    models.TextField(db_column="second_name", max_length=50),
                ),
                ("Address", models.TextField(db_column="address", max_length=100)),
                ("country", models.IntegerField(db_column="country")),
                ("price", models.IntegerField(db_column="price")),
                ("contact", models.IntegerField(db_column="contact")),
                ("email", models.TextField(db_column="email", max_length=50)),
                (
                    "account_no",
                    models.TextField(db_column="account no", max_length=50, null=True),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="ifsc code", max_length=50, null=True),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank name", max_length=50, null=True),
                ),
                (
                    "image",
                    models.ImageField(db_column="guide_image", upload_to="images/"),
                ),
            ],
            options={
                "db_table": "add_guide",
            },
        ),
    ]
