# Generated by Django 4.1.7 on 2023-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0003_remove_add_vehicle_account_no_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Add_guide",
        ),
        migrations.DeleteModel(
            name="Catagory",
        ),
    ]
