# Generated by Django 4.1.7 on 2023-09-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0003_guide_book_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel_book",
            name="hotel_id",
            field=models.ForeignKey(
                db_column="hotel_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hgv.hotels",
            ),
        ),
    ]
