# Generated by Django 4.1.7 on 2023-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0005_add_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_name",
                    models.TextField(db_column="_vehiclename", max_length=50),
                ),
                ("vehicle_id", models.TextField(db_column="_vehicleid", max_length=50)),
                ("model", models.IntegerField(db_column="_model")),
                ("price", models.IntegerField(db_column="_price")),
                ("address", models.TextField(db_column="_address", max_length=50)),
                ("contact", models.IntegerField(db_column="_contact")),
                ("email", models.TextField(db_column="_email", max_length=50)),
                ("features", models.TextField(db_column="_features", max_length=50)),
                (
                    "account_no",
                    models.TextField(db_column="_account no", max_length=50, null=True),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="_ifsc code", max_length=50, null=True),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="_bank name", max_length=50, null=True),
                ),
                (
                    "vehicle_image",
                    models.ImageField(db_column="_vehicleimage", upload_to="images/"),
                ),
            ],
            options={
                "db_table": "add_vehicle",
            },
        ),
        migrations.AlterField(
            model_name="add_hotel",
            name="hotel_name",
            field=models.TextField(db_column="_hotelname", max_length=50),
        ),
    ]
