# Generated by Django 4.1.7 on 2023-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0006_add_vehicle_alter_add_hotel_hotel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_vehicle",
            name="model",
            field=models.TextField(db_column="_model"),
        ),
        migrations.AlterField(
            model_name="add_vehicle",
            name="vehicle_id",
            field=models.IntegerField(db_column="_vehicleid", max_length=50),
        ),
    ]
