# Generated by Django 4.1.7 on 2023-06-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0008_alter_add_vehicle_vehicle_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_guide",
            name="country",
            field=models.TextField(db_column="country"),
        ),
    ]
