# Generated by Django 4.1.7 on 2023-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0009_alter_add_guide_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_guide",
            name="contact",
            field=models.IntegerField(db_column="contact", max_length=13),
        ),
    ]
