# Generated by Django 4.1.7 on 2023-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0010_alter_add_guide_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_guide",
            name="contact",
            field=models.IntegerField(db_column="contact"),
        ),
    ]
