# Generated by Django 4.1.7 on 2023-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0012_alter_add_guide_contact_alter_add_hotel_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="add_hotel",
            name="rooms",
            field=models.TextField(db_column="rooms_available", null=True),
        ),
    ]
