# Generated by Django 4.1.7 on 2023-08-18 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0013_add_hotel_rooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                ("first_name", models.TextField(db_column="f_name", max_length=30)),
                ("last_name", models.TextField(db_column="l_name", max_length=30)),
                ("gender", models.CharField(db_column="gender", max_length=6)),
                ("dateofbirth", models.DateField(db_column="date_of_birth")),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                (
                    "address",
                    models.TextField(db_column="company_address", max_length=50),
                ),
                (
                    "country",
                    models.TextField(db_column="company_country", max_length=50),
                ),
                ("mobile", models.TextField(db_column="mobile_number", max_length=50)),
                ("email", models.TextField(db_column="company_email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "guides",
            },
        ),
        migrations.CreateModel(
            name="Hotels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                (
                    "companyname",
                    models.TextField(db_column="company_name", max_length=50),
                ),
                ("reg_id", models.TextField(db_column="company_reg_id", max_length=50)),
                (
                    "reg_year",
                    models.TextField(db_column="company_reg_year", max_length=50),
                ),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                ("address", models.TextField(db_column="address", max_length=50)),
                ("country", models.TextField(db_column="country", max_length=50)),
                ("mobile", models.TextField(db_column="mobile", max_length=50)),
                ("email", models.TextField(db_column="email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "Hotels",
            },
        ),
        migrations.CreateModel(
            name="vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usercatagory",
                    models.TextField(db_column="user_catagory", max_length=50),
                ),
                (
                    "companyname",
                    models.TextField(db_column="company_name", max_length=50),
                ),
                ("regid", models.TextField(db_column="company_reg_id", max_length=50)),
                (
                    "regyear",
                    models.TextField(db_column="company_reg_year", max_length=50),
                ),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "bank_name",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                ("address", models.TextField(db_column="address", max_length=50)),
                ("country", models.TextField(db_column="country", max_length=50)),
                ("mobile", models.TextField(db_column="mobile", max_length=50)),
                ("email", models.TextField(db_column="email", max_length=50)),
                ("user_id", models.IntegerField(db_column="login_id", null=True)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
            },
        ),
    ]
