# Generated by Django 4.1.7 on 2023-08-18 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0014_guides_hotels_vehicles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicles",
            old_name="regid",
            new_name="reg_id",
        ),
        migrations.RenameField(
            model_name="vehicles",
            old_name="regyear",
            new_name="reg_year",
        ),
    ]
