# Generated by Django 4.1.7 on 2023-08-18 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hgv", "0015_rename_regid_vehicles_reg_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="hotels",
            table="hotels",
        ),
    ]
